# Default values for ddhub-client-gateway-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
ddhub-client-gateway-api:
  replicaCount: 1

  clientgateway:
    config:
      # -- The URL of the DSB Message Broker you want to connect to. Trailing / allowed.
      dsb_base_url: https://trial.der.aemo.com.au/ddhub
      parent_namespace: ddhubtrial.apps.aemo.iam.ewc
      secret_engine: azure
      # -- Sets the secret prefix in the secret engine.
      secret_prefix: "ddhubtrial/"
      node_env: production
      opentelemetry_enabled: false
    scheduler:
      enabled: true
      image:
        repository: aemocontainerregistry.azurecr.io/ddhub-client-gateway-scheduler
        pullPolicy: IfNotPresent
        # Overrides the image tag whose default is the chart appVersion.
        tag: latest
      appConfig:
        NO_COLOR: "true"
    ui:
      enabled: true
      replicaCount: 1
      image:
        repository: aemocontainerregistry.azurecr.io/ddhub-client-gateway-frontend
        pullPolicy: IfNotPresent
        # Overrides the image tag whose default is the chart appVersion.
        tag: latest
  image:
    # repository: 098061033856.dkr.ecr.us-east-1.amazonaws.com/ew-dos-dsb-ecr
    repository: aemocontainerregistry.azurecr.io/ddhub-client-gateway-backend
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest

  imagePullSecrets: []
  nameOverride: "ddhub-client-gateway-trial"
  fullnameOverride: "ddhub-client-gateway-trial"

  podSecurityContext:
    fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      cert-manager.io/issuer: prod-issuer
      cert-manager.io/issuer-kind: OriginIssuer
      cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
      cert-manager.io/duration: 90d
      cert-manager.io/renew-before: 30d  
    hosts:
      - host: ddhub-gateway-trial.energyweb.org
        paths:
        - path: /docs
          pathType: Prefix
          backend:
            serviceName: ddhub-client-gateway-trial
            servicePort: 80
        - path: /api
          pathType: Prefix
          backend:
            serviceName: ddhub-client-gateway-trial
            servicePort: 80
        - path: /docs-json
          pathType: Prefix
          backend:
            serviceName: ddhub-client-gateway-trial
            servicePort: 80
        - path: /
          pathType: Prefix
          backend:
            serviceName: ddhub-client-gateway-trial-ui
            servicePort: 80
    tls:
      - secretName: ddhub-client-gateway-trial-tls-secret
        hosts:
          - ddhub-gateway-trial.energyweb.org

  probes:
    liveness: true
    livenessInitialDelay: 120
    livenessPeriodSeconds: 10
    readiness: true
    readinessInitialDelay: 120
